service_name: travis-ci
repo_token: p7zWhntZXnzvYTYwSkLaDwTT5QOYUQnNt
src_dir: typo3conf/ext/ajaxmap
coverage_clover: build/artifacts/coverage/clover.xml
json_path: build/artifacts/logs/coveralls-upload.json
